name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14.x]
        os: [ubuntu-latest]

    steps:
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Downloads Checkouts...
        uses: actions/checkout@v2

      - name: Create Firebase Configuration for Neon K.I.D
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG > src/components/Server/firebase/config.json

      - name: N.K Portpolio Build...
        run: |
          npm install
          npm run build:css
          npm run build

      - name: Deploy firebase live channel (Production)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NK_PROJECT_8EC03 }}'
          channelId: live
          projectId: nk-project-8ec03
