name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Firebase Configuration for Neon K.I.D
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          run: |
            echo $FIREBASE_CONFIG > src/components/Server/firebase/config.json
      - name: Initialize CodeQL..
        uses: github/codeql-action/init@v1
        with:
          languages: [javascript]
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      - name: N.K Portpolio Build...
      - run: |
          npm install
          npm run build:css
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NK_PROJECT_8EC03 }}'
          channelId: live
          projectId: nk-project-8ec03
